### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Salicorne** [OeilGlauque/oeilglauque.fr#1]
- [x] Modification du texte affiché quand les parties sont pleines
- [x] Masquer les places disponnibles dans une partie quand le joueur est inscrit
- [x] Ordonner les parties par créneau
- [x] Vérifier le nombre de parties max par créneau lors de l'ajout d'une nouvelle partie
- [x] Limiter la taille des parties affichées en liste
- [x] Permettre aux utilisateurs de modifier leur mot de passe
- [ ] Utiliser des icones quand c'est possible
- [ ] Ajouter la section métrologie à l'interface d'administration
- [ ] Vérification de l'adresse mail lors de l'inscription
- [ ] Afficher les photos en carousel

**Comment by raza6** [comment]
Outdated
